services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - myapp:/app/data
    environment:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  myapp: